apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
      - name: task-service
        image: task-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000  # Flask app runs on port 5000
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/todo"
---
apiVersion: v1
kind: Service
metadata:
  name: task-service
spec:
  type: NodePort
  selector:
    app: task-service
  ports:
    - protocol: TCP
      port: 80  # External port (NodePort)
      targetPort: 5000  # Map to container port 5000 where Flask runs
      nodePort: 30007  # External access
