apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
      - name: task-service
        image: task-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/todo"
        - name: NOTIFICATION_SERVICE_URL
          value: "http://notification-service/notify"
        - name: KUBERNETES_SERVICE_HOST
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: task-service
spec:
  type: LoadBalancer
  selector:
    app: task-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007